import { EffectRegistry } from './EffectRegistry';
import { chromaticAberrationDef } from './templates/ChromaticAberrationEffect';
import { bloomDef } from './templates/BloomEffect';
import { filmGrainDef } from './templates/FilmGrainEffect';
import { glitchDef } from './templates/GlitchEffect';
import { depthOfFieldDef } from './templates/DepthOfFieldEffect';
import { colorGradingDef } from './templates/ColorGradingEffect';
import { vignetteDef } from './templates/VignetteEffect';
import { pixelationDef } from './templates/PixelationEffect';
import { sepiaDef } from './templates/SepiaEffect';
import { scanlinesDef } from './templates/ScanlinesEffect';
import { outlineDef } from './templates/OutlineEffect';
import { ssaoDef } from './templates/SSAOEffect';

EffectRegistry.register(chromaticAberrationDef);
EffectRegistry.register(bloomDef);
EffectRegistry.register(glitchDef);
EffectRegistry.register(filmGrainDef);
EffectRegistry.register(depthOfFieldDef);
EffectRegistry.register(colorGradingDef);
EffectRegistry.register(vignetteDef);
EffectRegistry.register(pixelationDef);
EffectRegistry.register(sepiaDef);
EffectRegistry.register(scanlinesDef);
EffectRegistry.register(outlineDef);
EffectRegistry.register(ssaoDef);
